version: '3.9'
services:
  votacao:
    build:
      context: .
      dockerfile: ./votacao.dockerfile
    container_name: votacao_server
    ports:
      - "50051:50051"
    depends_on:
      - redis

  celery_worker:
    build:
      context: .
      dockerfile: ./celery.dockerfile
    container_name: votacao_celery
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: votacao_redis
    ports:
      - "6379:6379"
