version: '3.9'

services:
  votacao:
    build:
      context: .
      dockerfile: ./docker/votacao.dockerfile
    container_name: votacao_server
    ports:
      - "50051:50051"
    depends_on:
      - redis
      - db
    environment:
      DATABASE_URL: postgresql://postgres:7962@db:5432/votacao

  celery_worker:
    build:
      context: .
      dockerfile: ./docker/celery.dockerfile
    container_name: votacao_celery
    depends_on:
      - redis
      - db
    environment:
      DATABASE_URL: postgresql://postgres:7962@db:5432/votacao

  db:
    image: postgres:16-alpine
    container_name: votacao_db
    environment:
      POSTGRES_DB: votacao
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7962
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: votacao_redis
    ports:
      - "6379:6379"

volumes:
    postgres-data:
      name: votacao_postgres_data
