# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: votacao.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'votacao.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rvotacao.proto\x12\x1avotacao.controllers.protos\"K\n\x0bVotoRequest\x12\x12\n\nid_eleicao\x18\x01 \x01(\x05\x12\x12\n\nid_eleitor\x18\x02 \x01(\x05\x12\x14\n\x0cid_candidato\x18\x03 \x01(\x05\"k\n\x0f\x43omprovanteVoto\x12\x1b\n\x13id_comprovante_voto\x18\x01 \x01(\t\x12\x12\n\nid_eleicao\x18\x02 \x01(\x05\x12\x11\n\tdata_voto\x18\x03 \x01(\t\x12\x14\n\x0c\x64\x61ta_geracao\x18\x04 \x01(\t\"s\n\x0cVotoResponse\x12\x0f\n\x07sucesso\x18\x01 \x01(\x08\x12\x10\n\x08mensagem\x18\x02 \x01(\t\x12@\n\x0b\x63omprovante\x18\x03 \x01(\x0b\x32+.votacao.controllers.protos.ComprovanteVoto\"$\n\x11VotoValidoRequest\x12\x0f\n\x07id_voto\x18\x01 \x01(\t\"6\n\x12VotoValidoResponse\x12\x0e\n\x06valido\x18\x01 \x01(\x08\x12\x10\n\x08mensagem\x18\x02 \x01(\t\")\n\x13\x45leicaoVotosRequest\x12\x12\n\nid_eleicao\x18\x01 \x01(\x05\"D\n\x08VotoInfo\x12\x0f\n\x07id_voto\x18\x01 \x01(\t\x12\x14\n\x0cid_candidato\x18\x02 \x01(\x05\x12\x11\n\tdata_voto\x18\x03 \x01(\t\"K\n\x14\x45leicaoVotosResponse\x12\x33\n\x05votos\x18\x01 \x03(\x0b\x32$.votacao.controllers.protos.VotoInfo2\xd2\x02\n\x0eVotacaoService\x12Z\n\x05Votar\x12\'.votacao.controllers.protos.VotoRequest\x1a(.votacao.controllers.protos.VotoResponse\x12n\n\rGetVotoValido\x12-.votacao.controllers.protos.VotoValidoRequest\x1a..votacao.controllers.protos.VotoValidoResponse\x12t\n\x0fGetEleicaoVotos\x12/.votacao.controllers.protos.EleicaoVotosRequest\x1a\x30.votacao.controllers.protos.EleicaoVotosResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'votacao_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VOTOREQUEST']._serialized_start=45
  _globals['_VOTOREQUEST']._serialized_end=120
  _globals['_COMPROVANTEVOTO']._serialized_start=122
  _globals['_COMPROVANTEVOTO']._serialized_end=229
  _globals['_VOTORESPONSE']._serialized_start=231
  _globals['_VOTORESPONSE']._serialized_end=346
  _globals['_VOTOVALIDOREQUEST']._serialized_start=348
  _globals['_VOTOVALIDOREQUEST']._serialized_end=384
  _globals['_VOTOVALIDORESPONSE']._serialized_start=386
  _globals['_VOTOVALIDORESPONSE']._serialized_end=440
  _globals['_ELEICAOVOTOSREQUEST']._serialized_start=442
  _globals['_ELEICAOVOTOSREQUEST']._serialized_end=483
  _globals['_VOTOINFO']._serialized_start=485
  _globals['_VOTOINFO']._serialized_end=553
  _globals['_ELEICAOVOTOSRESPONSE']._serialized_start=555
  _globals['_ELEICAOVOTOSRESPONSE']._serialized_end=630
  _globals['_VOTACAOSERVICE']._serialized_start=633
  _globals['_VOTACAOSERVICE']._serialized_end=971
# @@protoc_insertion_point(module_scope)
